### COLUMN 생성
POST /api/board/{{boardId}}/stats
Host: localhost:8080
Content-Type: application/json
Authorization:{{accessToken}}
RefreshToken: {{refreshToken}}

{
  "title": "COLUMN생성입니다."
}

> {%
 client.global.set("statId", response.body.result.statId)
 %}

###
PUT /api/board/{{boardId}}/stats/{{statId}}
Host: localhost:8080
Content-Type: application/json
Authorization: {{accessToken}}
RefreshToken: {{refreshToken}}

{
  "title": "COLUMN 수정입니다."
}

###
DELETE /api/board/{{boardId}}/stats/{{statId}}
Host: localhost:8080
Content-Type: application/json
Authorization: {{accessToken}}
RefreshToken: {{refreshToken}}

{
  "title": "COLUMN 삭제입니다."
}