### USER 회원가입
POST localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username2",
  "password" : "password12!!",
  "email": "user2@gmail.com",
  "nickname": "UserName"
}

### MANAGER 회원가입
POST localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "manager",
  "password" : "password12!!",
  "email": "manager@gmail.com",
  "nickname": "ManagerName",
  "manager" : "zhemtpwnfdpsmseoajflrkdlTek"
}

### 이메일 전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "user1@gmail.com"
}

### 이메일 검증
PUT http://localhost:8080/users/email/verification
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "code": "Vxfmj7iw"
}

### USER 로그인
POST localhost:8080/users/login
Content-Type: application/json

{
  "username" : "username",
  "password" : "password12!!"
}

> {%
    client.global.set("accessToken", response.headers.valueOf("Authorization"))
    client.global.set("refreshToken", response.headers.valueOf("RefreshToken"))
%}

### MANAGER 로그인
POST localhost:8080/users/login
Content-Type: application/json

{
  "username" : "manager",
  "password" : "password12!!"
}

> {%
    client.global.set("accessToken", response.headers.valueOf("Authorization"))
    client.global.set("refreshToken", response.headers.valueOf("RefreshToken"))
 %}

### 토큰 재발급
GET localhost:8080/users/reissue
Content-Type: application/json
Authorization: {{accessToken}}
RefreshToken: {{refreshToken}}

> {%
    client.global.set("accessToken", response.headers.valueOf("Authorization"))
    client.global.set("refreshToken", response.headers.valueOf("RefreshToken"))
%}

### 로그아웃
GET localhost:8080/users/logout
Content-Type: application/json
Authorization: {{accessToken}}
RefreshToken: {{refreshToken}}

### test
GET localhost:8080/users/manager-test
Content-Type: application/json
Authorization: {{accessToken}}