### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 1-1. 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username" : "username1",
  "password" : "password12!!",
  "email": "user@gmail.com",
  "nickname": "nickname"
}

### 1-2. 이메일 전송
POST http://localhost:8080/users/email
Content-Type: application/json

{
  "email": "user@gmail.com"
}

### 1-3. 이메일 검증
PUT http://localhost:8080/users/email/verification
Content-Type: application/json

{
  "email": "user@gmail.com",
  "code": "YG2WlVU3"
}
